version: '3.8'

services:
  backend:
    image: collecting_contacts_clone-backend:v1.0-stable
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PROXYAPI_KEY=${PROXYAPI_KEY}
      - PROXYAPI_BASE_URL=${PROXYAPI_BASE_URL}
    volumes:
      - ./backend:/app

  frontend:
    image: collecting_contacts_clone-frontend:v1.0-stable
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
